-- This file is no longer the primary schema.
-- Migrations are now in: supabase/migrations/
--
-- To apply:
--   1. supabase link --project-ref <your-project-ref>
--   2. supabase db push
--
-- Your project ref is in the Supabase dashboard URL:
--   https://supabase.com/dashboard/project/<project-ref>
-- Or from Project Settings > General > Reference ID
--
-- If you have 2 projects, supabase db push only affects
-- the one you linked with supabase link. It does NOT use
-- your .env.local keys for this.
